version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - redis
      - mongodb
    env_file:
      - .env
    restart: always
    #networks:
    #  - krista-dev
  redis:
    image: 'bitnami/redis:6.2.13'
    expose:
      - 6379
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - krista-dev

  mongodb:
    container_name: "mongodb"
    image: bitnami/mongodb
    hostname: mongodb
    restart: always
    volumes:
      - mongo-data2:/bitnami/mongodb
    environment:
      - MONGODB_ROOT_USER=aboba
      - MONGODB_ROOT_PASSWORD=aboba
      - MONGODB_DATABASE=krista
    ports:
      - 27017:27017
    networks:
      - krista-dev
volumes:
  mongo-data2:
  static:
#networks:
#  krista-dev:
#    external: true
