name: Workflow для развертывания dev окружения

on:
  push:
    branches: [ "dev" ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: startupcifra
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Decode vizme secrets
        run: echo "${{ secrets.VIZME_FIREBASE_SECRETS}}" | base64 --decode > vizme_firebase_secrets.json
      - name: Build the Docker image
        run: docker build . -t startupcifra/vizme-backend:$(git rev-parse --short "$GITHUB_SHA")
      - name: Push the Docker image
        run: docker push startupcifra/vizme-backend:$(git rev-parse --short "$GITHUB_SHA")
    